variables:
  MODULE_NAME: serversecure.core
  DEPENDENCIES: $(System.DefaultWorkingDirectory)/dependencies
  GARRYSMOD_COMMON: $(System.DefaultWorkingDirectory)/dependencies/garrysmod_common
  GARRYSMOD_COMMON_BRANCH: master
  GARRYSMOD_COMMON_REPOSITORY: https://github.com/danielga/garrysmod_common.git
  PROJECT_GENERATOR_VERSION: 2
  REPOSITORY_DIR: $(System.DefaultWorkingDirectory)
trigger:
  tags:
    include:
    - '*'
jobs:
- job: windows
  displayName: Windows
  pool:
    name: Azure Pipelines
    vmImage: windows-2019
  timeoutInMinutes: 10
  variables:
    BOOTSTRAP_URL: https://raw.githubusercontent.com/danielga/garrysmod_common/master/build/bootstrap.ps1
    BUILD_SCRIPT: $(System.DefaultWorkingDirectory)/dependencies/garrysmod_common/build/build.ps1
    COMPILER_PLATFORM: vs2019
    PROJECT_OS: windows
    PREMAKE5: $(System.DefaultWorkingDirectory)/dependencies/windows/premake-core/premake5.exe
    PREMAKE5_URL: https://github.com/premake/premake-core/releases/download/v5.0.0-alpha15/premake-5.0.0-alpha15-windows.zip
  steps:
  - powershell: 'Invoke-Expression ((New-Object System.Net.WebClient).DownloadString("$env:BOOTSTRAP_URL"))'
    displayName: Bootstrap
  - powershell: '& "$env:BUILD_SCRIPT"'
    displayName: Build
  - task: CopyFiles@2
    displayName: 'Copy files to $(Build.ArtifactStagingDirectory)'
    inputs:
      SourceFolder: '$(System.DefaultWorkingDirectory)/projects/windows/vs2019'
      Contents: '*/Release/*.dll'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      CleanTargetFolder: true
      flattenFolders: true
      preserveTimestamp: true
  - task: PublishBuildArtifacts@1
    displayName: 'Publish build artifacts'
    inputs:
      ArtifactName: windows
